### PR TITLE
update README

### PR DESCRIPTION
**Pull request by aorzh**
Need update example as `from lib.google_search_results ...` a bit confused

### CODE REVIEW

**Comment by lukeorland** [comment]
It looks like they fixed this and you can close this PR.

**Comment by aorzh** [comment]
Yeah, you right
Going to close it :)

**Comment by hartator** [comment]
@aorzh Thanks for the PR! Sorry it took a while to fix the Readme.

**Comment by aorzh** [comment]
@hartator no prob! Not so critical issue :)

**Pull request closed without merging**
